/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/_studio'
import { Route as StudioIndexRouteImport } from './routes/_studio/index'
import { Route as StudioChatRouteImport } from './routes/_studio/chat'
import { Route as StudioPanelRouteImport } from './routes/_studio/panel'
import { Route as StudioPeopleRouteImport } from './routes/_studio/people'
import { Route as StudioPhotosRouteImport } from './routes/_studio/photos'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'

const StudioRoute = StudioRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioChatRoute = StudioChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPanelRoute = StudioPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPeopleRoute = StudioPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPhotosRoute = StudioPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => StudioRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StudioIndexRoute
  '/chat': typeof StudioChatRoute
  '/panel': typeof StudioPanelRoute
  '/people': typeof StudioPeopleRoute
  '/photos': typeof StudioPhotosRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telegram': typeof ApiTelegramRoute
}
export interface FileRoutesByTo {
  '/chat': typeof StudioChatRoute
  '/panel': typeof StudioPanelRoute
  '/people': typeof StudioPeopleRoute
  '/photos': typeof StudioPhotosRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_studio': typeof StudioRouteWithChildren
  '/_studio/chat': typeof StudioChatRoute
  '/_studio/panel': typeof StudioPanelRoute
  '/_studio/people': typeof StudioPeopleRoute
  '/_studio/photos': typeof StudioPhotosRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/_studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/panel'
    | '/people'
    | '/photos'
    | '/api/health'
    | '/api/telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/panel'
    | '/people'
    | '/photos'
    | '/api/health'
    | '/api/telegram'
    | '/'
  id:
    | '__root__'
    | '/_studio'
    | '/_studio/chat'
    | '/_studio/panel'
    | '/_studio/people'
    | '/_studio/photos'
    | '/api/health'
    | '/api/telegram'
    | '/_studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StudioRoute: typeof StudioRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/': {
      id: '/_studio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/chat': {
      id: '/_studio/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof StudioChatRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/panel': {
      id: '/_studio/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof StudioPanelRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/people': {
      id: '/_studio/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof StudioPeopleRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/photos': {
      id: '/_studio/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof StudioPhotosRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioChatRoute: typeof StudioChatRoute
  StudioPanelRoute: typeof StudioPanelRoute
  StudioPeopleRoute: typeof StudioPeopleRoute
  StudioPhotosRoute: typeof StudioPhotosRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioChatRoute: StudioChatRoute,
  StudioPanelRoute: StudioPanelRoute,
  StudioPeopleRoute: StudioPeopleRoute,
  StudioPhotosRoute: StudioPhotosRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StudioRoute: StudioRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiTelegramRoute: ApiTelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
